// Cart
export const SET_CART_COUNT = 'SET_CART_COUNT';
export const SET_CART = 'SET_CART';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const SET_TIP = 'SET_TIP';
export const SET_SELECTED_MODE_PAYMENT = 'SET_SELECTED_MODE_PAYMENT';
export const SET_PROMO_CODE = 'SET_PROMO_CODE';
export const SET_DELIVERY_OPTION = 'SET_DELIVERY_OPTION';
export const REDUCE_CART_ITEM = 'REDUCE_CART_ITEM';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
// PUBLIC
export const SET_USER = 'SET_USER';
export const SET_ORDER_PROCESSING_DATE = 'SET_ORDER_PROCESSING_DATE';
export const SET_SELECTED_ADDRESS = 'SET_SELECTED_ADDRESS';